# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(441, 587)
        Form.setStyleSheet("#Form{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.869, y2:0.403818, stop:0 rgba(46, 183, 169, 255), stop:1 rgba(255, 146, 255, 255));\n"
"}\n"
"QLabel{\n"
"    \n"
"    font: 10pt \"Gadugi\";\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(50, 50, 50, 50)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_main = QtWidgets.QFrame(Form)
        self.frame_main.setStyleSheet("#frame_main{\n"
"    border-radius: 12;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame_main)
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("arrow_back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.frame_main)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 16pt \"Gadugi\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 10)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.le_login = QtWidgets.QLineEdit(self.frame_main)
        self.le_login.setStyleSheet("border-radius: 5;\n"
"border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0.869, y2:0.403818, stop:0 rgba(46, 183, 169, 255), stop:1 rgba(255, 146, 255, 255));\n"
"padding: 2;")
        self.le_login.setObjectName("le_login")
        self.verticalLayout.addWidget(self.le_login)
        self.label_4 = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.le_name = QtWidgets.QLineEdit(self.frame_main)
        self.le_name.setStyleSheet("border-radius: 5;\n"
"border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0.869, y2:0.403818, stop:0 rgba(46, 183, 169, 255), stop:1 rgba(255, 146, 255, 255));\n"
"padding: 2;")
        self.le_name.setObjectName("le_name")
        self.verticalLayout.addWidget(self.le_name)
        self.label_3 = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.le_pwd = QtWidgets.QLineEdit(self.frame_main)
        self.le_pwd.setStyleSheet("border-radius: 5;\n"
"border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0.869, y2:0.403818, stop:0 rgba(46, 183, 169, 255), stop:1 rgba(255, 146, 255, 255));\n"
"padding: 2;")
        self.le_pwd.setObjectName("le_pwd")
        self.verticalLayout.addWidget(self.le_pwd)
        self.label_5 = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.le_r_pwd = QtWidgets.QLineEdit(self.frame_main)
        self.le_r_pwd.setStyleSheet("border-radius: 5;\n"
"border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0.869, y2:0.403818, stop:0 rgba(46, 183, 169, 255), stop:1 rgba(255, 146, 255, 255));\n"
"padding: 2;")
        self.le_r_pwd.setObjectName("le_r_pwd")
        self.verticalLayout.addWidget(self.le_r_pwd)
        self.label_6 = QtWidgets.QLabel(self.frame_main)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.cb_hobby = QtWidgets.QComboBox(self.frame_main)
        self.cb_hobby.setStyleSheet("QComboBox{\n"
"border-radius: 5;\n"
"border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0.869, y2:0.403818, stop:0 rgba(46, 183, 169, 255), stop:1 rgba(255, 146, 255, 255));\n"
"padding: 2;\n"
"}\n"
"QComboBox::drop-down { \n"
"height: 0px;                    \n"
"width: 0px;\n"
"                    \n"
"                     }")
        self.cb_hobby.setIconSize(QtCore.QSize(16, 16))
        self.cb_hobby.setFrame(True)
        self.cb_hobby.setObjectName("cb_hobby")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.cb_hobby.addItem("")
        self.verticalLayout.addWidget(self.cb_hobby)
        self.label_7 = QtWidgets.QLabel(self.frame_main)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.pte_about = QtWidgets.QPlainTextEdit(self.frame_main)
        self.pte_about.setStyleSheet("border-radius: 5;\n"
"border: 1px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0.869, y2:0.403818, stop:0 rgba(46, 183, 169, 255), stop:1 rgba(255, 146, 255, 255));\n"
"padding: 2;")
        self.pte_about.setObjectName("pte_about")
        self.verticalLayout.addWidget(self.pte_about)
        spacerItem1 = QtWidgets.QSpacerItem(17, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pb_next = QtWidgets.QPushButton(self.frame_main)
        self.pb_next.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.869, y2:0.403818, stop:0 rgba(46, 183, 169, 255), stop:1 rgba(255, 146, 255, 255));\n"
"border: none;\n"
"border-radius: 10;\n"
"padding: 7;\n"
"}\n"
"QPushButton:hover:pressed{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 16, 225, 255), stop:1 rgba(255, 72, 255, 255));\n"
"    color:  white;\n"
"}")
        self.pb_next.setObjectName("pb_next")
        self.verticalLayout.addWidget(self.pb_next)
        spacerItem2 = QtWidgets.QSpacerItem(20, 14, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame_main, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "РЕГИСТРАЦИЯ"))
        self.label_2.setText(_translate("Form", "Придумайте логин:"))
        self.label_4.setText(_translate("Form", "Укажите имя:"))
        self.label_3.setText(_translate("Form", "Придумайте пароль:"))
        self.label_5.setText(_translate("Form", "Повторите пароль:"))
        self.label_6.setText(_translate("Form", "Укажите хобби:"))
        self.cb_hobby.setItemText(0, _translate("Form", "Не выбрано"))
        self.cb_hobby.setItemText(1, _translate("Form", "Путешествия"))
        self.cb_hobby.setItemText(2, _translate("Form", "Спорт"))
        self.cb_hobby.setItemText(3, _translate("Form", "Исскуство"))
        self.cb_hobby.setItemText(4, _translate("Form", "Пение"))
        self.cb_hobby.setItemText(5, _translate("Form", "Танцы"))
        self.cb_hobby.setItemText(6, _translate("Form", "Настольные игры"))
        self.cb_hobby.setItemText(7, _translate("Form", "Компьютерные игры"))
        self.cb_hobby.setItemText(8, _translate("Form", "Чтение"))
        self.cb_hobby.setItemText(9, _translate("Form", "Другое"))
        self.label_7.setText(_translate("Form", "Расскажите о себе:"))
        self.pb_next.setText(_translate("Form", "Продолжить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
